### ISSUE TITLE
#feature: Continue development of the Preprocessing pipeline driver script

### ISSUE THREAD

**Issue by J-glove** [uf-hobi-informatics-lab/SPACESCANS#41]
The script has been verified for only UCR.
Please do the following:

- attempt to run this pipeline on other datasources
- Draft a readme on how to run this script
- Prepare a demo of running this script on a datasource (preferably not UCR, for the 11/13 meeting)

**Comment by chengrong-us** [comment]
Updates:
1. FARA_formatting.py has been revised and works well. 
Revised the "args.raw_data_path" functions in FARA_formatting.py to accept multiple raw data paths and fixed the bug can not subtract year in "extract_year_from_filename(file_path)" function. 
2. But the path can not be passed to FARA_formatting.py from preprocess_pipeline.py.

Plan:
1. Continue revising the arg function in preprocess_pipeline.py.

**Comment by chengrong-us** [comment]
Updates (2024-12-17):

1. The preprocessing pipeline driver script now works well for FARA. 
I have fixed the bugs that prevented multiple file paths from being passed to FARA_formatting.py. Now, we can run FARA_formatting.py independently from the command line, as well as execute it through preprocess_pipeline.py.
2. Not push it to GitHub.
3. Continue to verify other kind of exposome.

**Comment by J-glove** [comment]
Sounds good, I am going to make verification a ticket for this script.
